name: Trigger dependencies cache

description: 'Saves the node_modules folder to cache'

runs:
  using: 'composite'
  steps:
    - uses: actions/cache@v3
      id: dependencies-cache
      with:
        path: node_modules
        key: node_modules-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          node_modules-

    - uses: pnpm/action-setup@v4
      name: Install pnpm
      with:
        run_install: false

    - name: Install dependencies
      if: steps.dependencies-cache.outputs.cache-hit != 'true'
      run: CI=true pnpm install
      shell: bash
